import { forwardRef, lazy, useMemo } from "react";
import type { ComponentType } from "react";

/**
 * WasteIcon — high-level wrapper that accepts an AVV code and renders
 * the matching outline waste icon.
 *
 * Lookup order:
 *   1. Exact 6-digit code match
 *   2. 4-digit group match (first 4 digits)
 *   3. 2-digit chapter match (first 2 digits)
 *   4. Generic fallback
 *
 * Usage:
 *   <WasteIcon code="170102" className="h-6 w-6 text-gray-500" />
 */

// ─── Code → component name mapping ─────────────────────────────────────────
// This maps AVV codes to the PascalCase component names generated by build-react.
// The actual components live in ./waste/outline/*.tsx

const codeMap: Record<string, string> = {
  // Chapter icons (2-digit)
  "01": "MiningIcon",
  "02": "AgricultureIcon",
  "03": "WoodPaperIcon",
  "04": "LeatherTextileIcon",
  "05": "PetroleumIcon",
  "06": "InorganicChemistryIcon",
  "07": "OrganicChemistryIcon",
  "08": "CoatingsPaintIcon",
  "09": "PhotographicIndustryIcon",
  "10": "ThermalProcessesIcon",
  "11": "SurfaceTreatmentIcon",
  "12": "MetalShapingIcon",
  "13": "WasteOilsIcon",
  "14": "SolventsIcon",
  "15": "PackagingIcon",
  "16": "MiscellaneousWasteIcon",
  "17": "ConstructionDemolitionIcon",
  "18": "MedicalWasteIcon",
  "19": "WasteTreatmentIcon",
  "20": "MunicipalWasteIcon",

  // Group icons (4-digit)
  "0101": "MineralExtractionIcon",
  "0103": "ProcessingResiduesIcon",
  "0104": "NonMetallicMineralsIcon",
  "0105": "DrillingMudsIcon",
  "0201": "AgricultureFarmingIcon",
  "0202": "MeatFishIcon",
  "0203": "FruitVegetablesIcon",
  "0204": "SugarProductionIcon",
  "0205": "DairyProcessingIcon",
  "0206": "BakeryConfectioneryIcon",
  "0207": "BeverageProductionIcon",
  "0301": "WoodworkingIcon",
  "0302": "WoodPreservativesIcon",
  "0303": "PaperPulpIcon",
  "0401": "LeatherIndustryIcon",
  "0402": "TextileIndustryIcon",
  "0501": "OilRefiningIcon",
  "0506": "CoalPyrolysisIcon",
  "0507": "GasPurificationIcon",
  "0601": "AcidsIcon",
  "0602": "BasesIcon",
  "0603": "SaltsMetalOxidesIcon",
  "0604": "MetalContainingWasteIcon",
  "0605": "SludgeWastewaterIcon",
  "0606": "SulfurChemistryIcon",
  "0607": "HalogenChemistryIcon",
  "0608": "SiliconIcon",
  "0609": "PhosphorusChemistryIcon",
  "0610": "NitrogenFertilizerIcon",
  "0611": "InorganicPigmentsIcon",
  "0613": "InorganicChemistryOtherIcon",
  "0701": "BasicOrganicChemicalsIcon",
  "0702": "PlasticsRubberIcon",
  "0703": "OrganicDyesIcon",
  "0704": "PesticidesBiocidesIcon",
  "0705": "PharmaceuticalsIcon",
  "0706": "FatsSoapsDetergentsIcon",
  "0707": "FineChemicalsIcon",
  "0801": "PaintsLacquersIcon",
  "0802": "SprayCoatingsIcon",
  "0803": "PrintingInkIcon",
  "0804": "AdhesivesSealantsIcon",
  "0805": "CoatingsOtherIcon",
  "0901": "PhotographicFilmIcon",
  "1001": "PowerPlantsIcon",
  "1002": "IronSteelIcon",
  "1003": "AluminiumMetallurgyIcon",
  "1004": "LeadMetallurgyIcon",
  "1005": "ZincMetallurgyIcon",
  "1006": "CopperMetallurgyIcon",
  "1007": "PreciousMetalsIcon",
  "1008": "NonFerrousMetallurgyIcon",
  "1009": "FoundryWasteIcon",
  "1010": "FoundryWasteNonFerrousIcon",
  "1011": "GlassManufacturingIcon",
  "1012": "CeramicsIcon",
  "1013": "CementConcreteIcon",
  "1014": "CrematoriumIcon",
  "1101": "ChemicalSurfaceTreatmentIcon",
  "1102": "HydrometallurgyIcon",
  "1103": "HardeningSludgeIcon",
  "1105": "HotDipGalvanisingIcon",
  "1201": "MechanicalShapingIcon",
  "1203": "SteamDegreasingIcon",
  "1301": "HydraulicOilsIcon",
  "1302": "EngineGearOilsIcon",
  "1303": "InsulatingOilsIcon",
  "1304": "BilgeOilsIcon",
  "1305": "OilWaterSeparatorIcon",
  "1307": "LiquidFuelsIcon",
  "1308": "WasteOilsOtherIcon",
  "1406": "OrganicSolventsIcon",
  "1501": "PackagingMaterialsIcon",
  "1502": "AbsorbentMaterialsIcon",
  "1601": "EndOfLifeVehiclesIcon",
  "1602": "ElectronicEquipmentIcon",
  "1603": "OffSpecBatchesIcon",
  "1604": "AmmunitionExplosivesIcon",
  "1605": "PressurisedGasCylindersIcon",
  "1606": "BatteriesIcon",
  "1607": "TankCleaningIcon",
  "1608": "SpentCatalystsIcon",
  "1609": "OxidisingAgentsIcon",
  "1610": "AqueousLiquidWasteIcon",
  "1611": "RefractoryLiningsIcon",
  "1701": "ConcreteBricksTilesIcon",
  "1702": "WoodGlassPlasticIcon",
  "1703": "AsphaltTarIcon",
  "1704": "MetalsIcon",
  "1705": "SoilDredgingIcon",
  "1706": "InsulationMaterialsIcon",
  "1708": "GypsumIcon",
  "1709": "MixedConstructionWasteIcon",
  "1801": "HumanMedicineIcon",
  "1802": "VeterinaryMedicineIcon",
  "1901": "IncinerationIcon",
  "1902": "PhysicoChemicalTreatmentIcon",
  "1903": "StabilisedWasteIcon",
  "1904": "VitrifiedWasteIcon",
  "1905": "CompostingIcon",
  "1906": "AnaerobicDigestionIcon",
  "1907": "LandfillLeachateIcon",
  "1908": "WastewaterTreatmentIcon",
  "1909": "DrinkingWaterTreatmentIcon",
  "1910": "ShredderIcon",
  "1911": "WasteOilRegenerationIcon",
  "1912": "SortingIcon",
  "1913": "SoilRemediationIcon",
  "2001": "SortedFractionsIcon",
  "2002": "GardenParkWasteIcon",
  "2003": "OtherMunicipalWasteIcon",

  // Code-specific icons (6-digit)
  "080111": "HazardousPaintIcon",
  "150102": "PlasticPackagingIcon",
  "150103": "WoodPackagingIcon",
  "150104": "MetalPackagingIcon",
  "150105": "CompositePackagingIcon",
  "150107": "GlassPackagingIcon",
  "170101": "ConcreteIcon",
  "170102": "BrickIcon",
  "170103": "TilesCeramicsIcon",
  "170106": "ContaminatedRubbleIcon",
  "170107": "RubbleIcon",
  "170201": "LumberIcon",
  "170202": "FlatGlassIcon",
  "170203": "ConstructionPlasticIcon",
  "170301": "TarryAsphaltIcon",
  "170302": "AsphaltIcon",
  "170303": "CoalTarIcon",
  "170405": "IronSteelScrapIcon",
  "170407": "MixedScrapIcon",
  "170410": "ContaminatedCablesIcon",
  "170411": "CablesIcon",
  "170503": "ContaminatedSoilIcon",
  "170504": "ExcavatedSoilIcon",
  "170506": "DredgingSpoilIcon",
  "170508": "TrackBallastIcon",
  "170601": "AsbestosInsulationIcon",
  "170605": "AsbestosBuildingMaterialsIcon",
  "170901": "MercuryConstructionWasteIcon",
  "170902": "PcbConstructionWasteIcon",
  "200101": "WastePaperIcon",
  "200102": "WasteGlassIcon",
  "200108": "BioWasteIcon",
  "200110": "OldClothesIcon",
  "200113": "HazardousSolventsIcon",
  "200121": "FluorescentTubesIcon",
  "200126": "CookingOilIcon",
  "200127": "HazardousPaintMunicipalIcon",
  "200128": "PaintMunicipalIcon",
  "200132": "MedicinesIcon",
  "200133": "HazardousBatteriesIcon",
  "200134": "BatteriesMunicipalIcon",
  "200135": "HazardousElectronicsIcon",
  "200136": "ElectronicsIcon",
  "200137": "HazardousWoodIcon",
  "200138": "WoodIcon",
  "200139": "PlasticsIcon",
  "200140": "ScrapMetalIcon",
  "200201": "GreenWasteIcon",
  "200301": "ResidualWasteIcon",
  "200303": "StreetSweepingsIcon",
  "200307": "BulkyWasteIcon",
};

// ─── Dynamic imports ────────────────────────────────────────────────────────

// Build a map of lazy-loaded components so we don't import everything upfront.
// For static / SSR usage, the build step ensures these are tree-shakeable.

type SvgComponent = ComponentType<React.SVGProps<SVGSVGElement>>;

const componentCache = new Map<string, SvgComponent>();

function getIconComponent(
  code: string
): SvgComponent | null {
  // 1. Exact code match
  if (codeMap[code]) {
    return resolveComponent(code);
  }

  // 2. Group match (first 4 digits)
  const group = code.slice(0, 4);
  if (codeMap[group]) {
    return resolveComponent(group);
  }

  // 3. Chapter match (first 2 digits)
  const chapter = code.slice(0, 2);
  if (codeMap[chapter]) {
    return resolveComponent(chapter);
  }

  return null;
}

function resolveComponent(key: string): SvgComponent | null {
  const name = codeMap[key];
  if (!name) return null;

  if (componentCache.has(name)) {
    return componentCache.get(name)!;
  }

  // For now, return null — in a full build, this would use dynamic imports
  // or a pre-built lookup. The static barrel exports are the recommended path.
  return null;
}

// ─── Fallback icon ──────────────────────────────────────────────────────────

const FallbackIcon = forwardRef<SVGSVGElement, React.SVGProps<SVGSVGElement>>(
  (props, ref) => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      ref={ref}
      {...props}
    >
      <circle
        cx="12"
        cy="12"
        r="9"
        stroke="currentColor"
        strokeWidth="1.5"
      />
      <path
        d="M12 8v5"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
      />
      <circle cx="12" cy="16" r="0.5" fill="currentColor" />
    </svg>
  )
);
FallbackIcon.displayName = "FallbackIcon";

// ─── WasteIcon component ────────────────────────────────────────────────────

export interface WasteIconProps extends React.SVGProps<SVGSVGElement> {
  /** AVV waste code (2, 4, or 6 digits) */
  code: string;
}

/**
 * Renders a waste icon for the given AVV code.
 *
 * For optimal tree-shaking, prefer importing individual icons directly:
 *   import { ConcreteIcon } from "@schaffsch/waste-icons/react/waste/outline";
 *
 * This wrapper is convenient when the code is dynamic (e.g. from a database).
 */
const WasteIcon = forwardRef<SVGSVGElement, WasteIconProps>(
  ({ code, ...props }, ref) => {
    const Icon = useMemo(() => getIconComponent(code), [code]);

    if (Icon) {
      return <Icon ref={ref} {...props} />;
    }

    return <FallbackIcon ref={ref} {...props} />;
  }
);

WasteIcon.displayName = "WasteIcon";

export default WasteIcon;

/**
 * Utility: get the component name for a given AVV code.
 * Useful for debugging or building custom lookups.
 */
export function getIconNameForCode(code: string): string | null {
  if (codeMap[code]) return codeMap[code];
  const group = code.slice(0, 4);
  if (codeMap[group]) return codeMap[group];
  const chapter = code.slice(0, 2);
  if (codeMap[chapter]) return codeMap[chapter];
  return null;
}

/**
 * All available AVV code → component name mappings.
 */
export const allCodeMappings = { ...codeMap } as Readonly<
  Record<string, string>
>;
